### ISSUE TITLE
Determine restrictions on the resource name

### ISSUE THREAD

**Issue by markboots** [FLOIP/flow-results#30]
> 1. ONA is expecting the resource element to contain a name that concatenates the package name to "-data". I couldn't find any specification requesting that. Would you point me to the specs that require that?

To my knowledge, neither the upstream Data Packages specification or the Flow Results specification puts any constraints on the resource name.

@ukanga , can you share if you know otherwise?  It seems like this was coming from the data packages python library you were using.  If this is necessary for Ona, we should discuss whether to require it within the spec.

**Comment by ukanga** [comment]
This seems to be a consistent theme in the examples I was looking at on . I will work on removing this requirement from the python package I implemented.

Is there a specific convention we should be following with regards to the `name` of the resource? It seems to be a required field.
```
A resource MUST contain a name property. The name is a simple name or identifier to be used for this resource.

    If present, the name MUST be unique amongst all resources in this data package.
    It MUST consist only of lowercase alphanumeric characters plus ".", "-" and "_".
    It would be usual for the name to correspond to the file name (minus the extension) of the data file the resource describes.
```
Considering we can have multiple resources does it mean each resource will need to be processed the same way or should we have a special case to handle or simply pick the first one?

Handling multiple resources for Ona might actually mean different forms and that might make it far much trickier in identifying which for the resource belongs to and may require us to define a unique `id` attribute for each resource with the `UUID` for the resource.

**Comment by markboots** [comment]
Agreed on call: name is required from the upstream spec, but we don't put any additional constraints on _what_ the name is.
