### ISSUE TITLE
Add milliseconds to timestamps

### ISSUE THREAD

**Issue by markboots** [FLOIP/flow-results#4]
Suggestion from @nicpottier to add milliseconds to timestamps in response row data.

Opening this issue to document the rationale.  Should it be recommended or required?  Should it apply to other timestamps (e.g.: the datetime or time question responses?)

**Comment by pld** [comment]
I'd suggest we recommend it and we have all our examples use it (as Nic
mentioned), the more data the better

**Comment by nicpottier** [comment]
Maybe the recommendation should just be that providers of results should include as much precision as they have and consumers must be able to parse arbitrary precision for timestamps. Consumers can always throw away precision if it doesn't interest them but seems we should encourage producers to not throw away anything they have.

**Comment by markboots** [comment]
Thumbs up here to Nic's suggestion.  Not all systems will have this, but we should encourage preserving any precision that is available.   I think it would be nice to allow data sources that don't have this precision to use 2017-07-06T13:56:78-04:00 instead of 2017-07-06T13:56:78.000-04:00.

**Comment by nicpottier** [comment]
Fractional seconds being optional sounds good me.

**Comment by markboots** [comment]
Sounds good! Resolved in https://github.com/FLOIP/flow-results/pull/2/commits/9811b832f3c4ce2dd85cebbc186179d388f52f43
