### ISSUE TITLE
Provide optional support for a Session ID

### ISSUE THREAD

**Issue by markboots** [FLOIP/flow-results#5]
Lots of systems track the concept of a session with the Contact.  It could be useful to have a common way of recording which Responses are associated with a session.

From @ggiraldez on https://github.com/FLOIP/flow-results/pull/2 :

> Do we want to indicate correlation of responses to a particular contact session with the capture tool? This would require a new column in the response rows. Should be optional since the concept of session would not be implement by all tools.

Some options we discussed on the call today:

- Option 1: add additional new (optional) column for session_id (column 7).  Pro: Avoids lots of repeated `session_id` text on each row.

- Option 2: allow putting `session_id: 2384728374` into the response metadata column JSON.  Pro: Most minor change.  Con: doesn't fit our current definition of response metadata, which is standardized data related to the Question type.

- Option 3: Add additional `extension` column for an extra JSON blob of whatever systems want to put there.  (Required column, can be `null` or `{}` if not needed). Includes whatever extensions vendor platforms want to include. One of these could be a `session_id`.  Pro: Most extensible solution; handles future request for a platform-specific place to store random things.   Question: do we have a standardized list of optional parameters (such as `session_id`), and require using an `X-` prefix for platform-specific parameters outside the standardized list?

I could live with all of these, as could the group on the call today.  @ewheeler picked option 3 for us from his 3-sided coin.  @nicpottier , @ukanga , do you have any suggestions?

**Comment by pld** [comment]
I don't think this is important, but I'd go w/option 2

**Comment by markboots** [comment]
Discussed today on call (2018-03-01):

- Ona needs it ; can't work without a session_id
- Are session IDs universal? Will all FLOIP applications have a session ID?
- Conversely, are there any situations we can think of without a session ID?

Proposal: because session IDs are (almost universally) common, make these a new first-order column in the spec.

Question: Should they be required, or can a platform send NULL for a session_id if it doesn't have that concept?

-- Hypothesis A: null is OK if you don't have a session-like concept... Ona will fill it in with e.g. the row ID, which will not be that helpful as every response will be seen as a separate submission
-- Hypothesis B: Avoid this because the data aggregator is changing the submitted data. Leave it up to the client to generate

On call, leaning to the proposal with Hypothesis A, as it would work with flexibility for the most systems.  However, we are optimizing for allowing no session IDs, and can't think of any application without session IDs. This seems funny.

@nditada , any thoughts?

**Comment by markboots** [comment]
Location of added column: insert after Column 3: 

- Timestamp
- Row ID
- Contact ID
- Session ID
- Question ID
- Response
- Metadata on response

**Comment by markboots** [comment]
Recapping our final decision from the group calls:

- Session ID is a primary column.
- To avoid implementation differences from the spec, it is required for all clients/servers. (Cannot be null)
- If there are any implementations that do not have a session ID... they can make one up, e.g. by using a concatenation of the contact ID and date of the response, or some other consistent method.  (Right now, we don't anticipate any use-cases that do not have a session concept.)

**Comment by markboots** [comment]
Fixed in https://github.com/FLOIP/flow-results/pull/27
